const { loginController, refreshUserToken } = require('./loginController');
const {
  userRegistration,
  postAdminUpdateUser,
  viewUser,
  adminDeleteUser,
  adminDeactivateUser,
  adminReactivateUser,
  getAdminDashboard,
  adminGetUser,
  postAdminCreateUser,
  filterUsers,
  adminUpdateProfile,
  updateProfile,
  adminViewUserProfile,
  getAdminCreateUser,
  getAdminUpdateUser,
  getRegisterComponent,
} = require('./userController');

const {
  getAdminGetTicket,
  getAdminCreateTicket,
  listTicket,
  updateTicket,
  deleteTicket,
  postCustomerCreateTicket,
  postAdminCreateTicket,
  getAdminEditTicket,
  patchAdminEditTicket,
  getCustomerListTickets,
  adminDeleteTicket,
  filterTickets,
  getCustomerRequestTickets,
  customerGetTicket,
  postUserConversation,
  postAdminConversation,
} = require('./ticketController');

const {
  createDepartment,
  getDepartment,
  deleteDepartment,
  adminUpdateDepartment,
  // viewDepartment,
  removeAgentFromDepartment,
  adminViewDepartment,
  deactivateDepartment,
  reactivateDepartment,
  getUpdateDepartment,
  getCreateDepartment,
  filterDepartments,
  getFilterDepartments,
} = require('./departmentController');
const resetPassword = require('./resetPasswordController');

const addAgentToDept = require('./manageAgentDept');
module.exports = {
  loginController,
  // ticket
  getAdminGetTicket,
  getAdminCreateTicket,
  listTicket,
  updateTicket,
  deleteTicket,
  postAdminCreateTicket,
  postCustomerCreateTicket,
  filterTickets,
  getCustomerListTickets,
  getCustomerRequestTickets,
  customerGetTicket,
  postUserConversation,
  postAdminConversation,
  // customer
  userRegistration,
  filterUsers,
  adminUpdateProfile,
  postAdminUpdateUser,
  viewUser,
  adminDeleteUser,
  adminDeactivateUser,
  adminReactivateUser,
  getAdminDashboard,
  adminGetUser,
  updateProfile,
  adminViewUserProfile,
  getAdminCreateUser,
  getAdminUpdateUser,
  getRegisterComponent,
  // department
  createDepartment,
  getDepartment,
  getCreateDepartment,
  deleteDepartment,
  adminUpdateDepartment,
  adminViewDepartment,
  deactivateDepartment,
  reactivateDepartment,
  getUpdateDepartment,
  deleteDepartment,
  filterDepartments,
  getFilterDepartments,
  // resetPassword
  resetPassword,
  removeAgentFromDepartment,
  addAgentToDept,
  postAdminCreateUser,
  refreshUserToken,
  // admin dashboard
  // viewDepartment,
  getAdminEditTicket,
  patchAdminEditTicket,
  adminDeleteTicket,
};
